name: Build APK with Ant

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Set up Android SDK
      uses: malinskiy/action-android/install-sdk@release/0.1.2
      
    - name: Build with Ant
      run: ant debug
      
    - name: Create output directory
      run: mkdir -p app/build/outputs/apk/debug
      
    - name: Copy APK to output directory
      run: cp bin/DRRRBotAndroidApp-debug.apk app/build/outputs/apk/debug/ || echo "APK not found"
      
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/DRRRBotAndroidApp-debug.apk